name: Time to Bake...

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]
    
env:
  ROM_URL: https://oxygenos.oneplus.net/OnePlus7Oxygen_13.W.41_OTA_041_all_2007291632_13a3db652ee04e29.zip
  ROM_NAME: OxygenOS
  ZIP_NAME: OxygenOS-Helios
  TZ: Middle-East/Kuwait
  MIR_NAME1: wet

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the workflow 
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python-dev
            sudo -E apt-get -qq install python
            sudo -E apt-get -qq install simg2img
            sudo -E apt-get -qq install python-protobuf
            python3 --version
      
       - name: processing ErfanGSIs code 
         run: git clone --recurse-submodules https://github.com/123ridhin/ErfanGSIs.git
       
       - name: Setting up requirements and permissions
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
                        
       - name: downloading the firmware
         run: sudo wget $ROM_URL -P ErfanGSIs
      
     
       - name: using dynamic.sh 
         run: cd ErfanGSIs && sudo ./md.sh OxygenOS OnePlus7Oxygen_13.W.41_OTA_041_all_2007291632_13a3db652ee04e29.zip
       - name: mounting the system.img
         run: cd ErfanGSIs/cache && sudo mkdir oos && sudo mount system.img oos
       
       - name: using make.sh 
         run: sudo ./ErfanGSIs/make.sh ErfanGSIs/cache/oos $ROM_NAME AB && sudo ./ErfanGSIs/make.sh ErfanGSIs/cache/oos $ROM_NAME Aonly
         
     
       - name: Zipping Aonly
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/out
              zip -r ErfanGSIs/out/$ZIP_NAME-HeliosGSIs-Aonly.7z ErfanGSIs/out/*-Aonly-*.img
             
       - name: uploading Aonly.zip
         run: |    
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR_NAME1 ErfanGSIs/out/$ZIP_NAME-HeliosGSIs-Aonly.7z 
                       
       - name: Zipping AB
         run: |
              zip -r ErfanGSIs/out/$ZIP_NAME-HeliosGSIs-AB.7z ErfanGSIs/out/*-AB-*.img
              
       - name: uploading AB.zip
         run: |
              ./transfer $MIR_NAME1 ErfanGSIs/out/$ZIP_NAME-HeliosGSIs-AB.7z   
          
              
       - name: Upload Build Informations and Baked:)
         run: |
              ./transfer $MIR_NAME1 ErfanGSIs/out/*-Aonly-*.txt
         

                                                  

  
         
     
