name: Time to Bake...

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]
    
env:
  ROM_URL: https://otafsg1.h2os.com/patch/amazone2/GLO/OnePlus7TProOxygen/OnePlus7TProOxygen_13.W.08_GLO_008_2009072125/OnePlus7TProOxygen_13.W.08_OTA_008_all_2009072125_7c0d51f3cf.zip
  ROM_NAME: OxygenOS
  ZIP_NAME: OxygenOS-Helios
  TZ: Middle-East/Kuwait
  MIR_NAME1: wet

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the workflow 
         run: |
              sudo -E apt-get -qq update
              sudo -E apt-get -qq install git openjdk-8-jdk wget
              sudo apt-get install wget
              sudo apt-get install p7zip-full
              sudo apt-get update -y
              sudo apt-get install -y simg2img
              sudo apt-get install python-pip
              sudo apt-get install python3-pip
      
       - name: processing ErfanGSIs code 
         run: git clone --recurse-submodules https://github.com/123ridhin/ErfanGSIs.git
       
       - name: Setting up requirements and permissions
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
                        
       - name: downloading the firmware
         run: sudo wget $ROM_URL -P ErfanGSIs
      
     
       - name: using dynamic.sh 
         run: cd ErfanGSIs && sudo ./dynamic.sh OxygenOS OnePlus7TProOxygen_13.W.08_OTA_008_all_2009072125_7c0d51f3cf.zip
       - name: Mounting 
         run: cd ErfanGSIs/cache && sudo mkdir oos && sudo mount system.img oos
      
       - name: using url2GSI 
         run: sudo ./ErfanGSIs/url2GSI.sh ErfanGSIs/cache/oos $ROM_NAME
         
     
       - name: Zipping Aonly
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/out/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/out/*-Aonly-*.img
             
       - name: uploading Aonly.zip
         run: |    
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR_NAME1 ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z 
                       
       - name: Zipping AB
         run: |
              zip -r ErfanGSIs/out/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
       - name: uploading AB.zip
         run: |
              ./transfer $MIR_NAME1 ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z   
          
              
       - name: Upload Build Informations and Baked:)
         run: |
              ./transfer $MIR_NAME1 ErfanGSIs/output/*-Aonly-*.txt
         

                                                  

  
         
     
